project:
  type: book
  output-dir: _output
execute:
  freeze: true

book:
  title: "Industry Policy"
  author:
    - "Gemma Beale"
    - "Hamish Gamble"
  date: "18/06/2025"
  downloads: [pdf, docx]
  chapters:
    - index.qmd
    - intro.qmd
    - part: planning.qmd
      chapters:
      - just-transitions.qmd
      - economic-complexity.qmd
      - procurement.qmd
    - part: future-of-work.qmd
      chapters:
      - steel-aluminium.qmd
      - wind-tower-construction.qmd
      - laboratories.qmd
      - aviation.qmd
      - defence.qmd
      - roadside-assist.qmd
      - construction-supply-chains.qmd
      - mine-servicing.qmd
      - food.qmd
      - iron-and-foundries.qmd
      - rail.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    fig-width: 6
    fig-asp: 0.618
    fig-format: svg
    toc: true
    theme:
      - cosmo
      - brand
  pdf:
    fig-width: 6
    fig-asp: 0.618
    documentclass: scrreprt
  docx: 
    fig-width: 6
    fig-asp: 0.618
    toc: true
     

editor: visual

custom-callout:
  bolsh:
    icon: true
    icon-symbol: "fa-hand-fist"
    color: "red"

