project:
  type: book
  output-dir: _output
  
execute: 
  freeze: auto

book:
  title: "Industry Policy"
  author:
    - "Gemma Beale"
    - "Hamish Gamble"
  date: "18/06/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - economic-complexity.qmd
    - just-transitions.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    fig-width: 6
    fig-asp: 0.618
    toc: true
    theme:
      - cosmo
      - brand
  pdf:
    fig-width: 6
    fig-asp: 0.618
    documentclass: scrreprt
  docx: 
    fig-width: 6
    fig-asp: 0.618
    toc: true
     

editor: visual

custom-callout:
  bolsh:
    icon: true
    icon-symbol: "fa-hand-fist"
    color: "red"

