# Defence

## Industry Overview

-   defence includes aircraft and other armored vehicle manufacturing as well as repair and maintenance services for these equipment.

<!-- -->

-   is the industry in growth or decline?

    -   employment

    -   output

    -   revenue

## Opportunities

**AUKUS**

-   the opportunity is probably gone, but prioritising/demanding local content and manufacturing opportunities for the subs rather than purchasing pre-built submarines.

-   3-5 have already been conceded as second hand US-built submarines.

**frigates**

-   BAE in South Australia

**offshore patrol vessels**

-   Austal in Western Australia.

**williamstown**

-   reopen the Williamstown dockyard as an advanced manufacturing common user facility.

-   this CUF could provide manufacturing jobs and extend the defence supply chain into Victoria - components for electronics and other systems.

<!-- -->

-   this industry is supported through industry policy.

-   AUKUS, shipbuilding, submarines. These are opportunities but face significant risks. One being the political situation in the US. We must strive for value-adding activities on shore. Not just purchasing built equipment.

-   most of the opportunities for growth are probably in naval shipbuilding. but some repair and maintenance of equipment as well.

-   

<!-- -->

-   what and where are the opportunities for growth?

**multi-employer bargaining**

Some industries like defence may be more readily able to enter into a co-operative workplace agreement covering a precinct.  It doesn’t require a special FWC authorisation (so you don’t have to worry about size and demonstrating the common interest)  but the trade-off for us is you can’t take industrial action in furtherance of your bargaining aims.  In any event, it may be useful as a Greenfields Agreement (ie when there are no employees hired yet) so the Union is negotiating with the employers directly.

-   on one hand - defence contractors are in competition and getting buy-in would be difficult. Excepting the big players like BAE/Thales etc, defence has significant scope for MEB

**same job same pay**

It is imperative that host employers have enterprise agreements in place before SJSP can even be contemplated.  So regardless of which industry we’re looking at, you would need to have some level of industrial maturity in place that there’s been an enterprise agreement. 

-   is there an opportunity to use multi-employer bargaining, same job same pay, or other tools?

-   is there an opportunity to use FMIA

## Conclusion

-   summary

-   any other issues
