# Iron and Steel

## Industry Overview

Steel manufacturing in Australia is captured primarily by the ANZSIC groups:

-   Iron and Steel Forging

-   Basic Ferrous Metal Manufacturing

-   Basic Ferrous Metal Product Manufacturing

-   Iron Smelting and Steel production is dominated by BlueScope Steel, who had almost 50% of the market share in 2025.

Overall, the iron and steel industries rely on demand in the residential construction, mining, vehicles, and infrastructure sectors to maintain revenue stability. All aspects of the industry are facing increasing pressures from low-cost imports, especially in the face of rising input costs in Australia. Additional uncertainty surrounding international trade policy clouds future investment decisions. Within the steel manufacturing and structural steel fabricating industries, pressures from automation and AI adoption have reduced wage costs and impacted the labour market. Future revenue growth in these sectors may rely on increased demand for green steel – indicating the importance for local manufacturers to invest in these production technologies now.

Both the iron and steel casting and forging industries have faced declining revenue over the last five years. Revenue has reduced at an annualized rate of 7.7%, primarily due to the continued impacts of the decline of the Australian motor vehicle manufacturing industry and increased import competition. In iron and steel forging, deteriorating conditions in mining output and railway equipment manufacturing has resulted in an annualised revenue decline of 2.4% through to 2024-25.

However, future growth is predicted as population growth increases pressure on existing infrastructure – increasing demand for multi-unit apartments, townhouses, and railway equipment. The completion of existing large infrastructure projects will dampen future sales without a strong pipeline of additional work. Finally, there is an opportunity through increased demand for wind farm construction to support the iron and steel forging industry.

## Opportunities

**what and where are the opportunities for growth?**

Most steel production in Australia occurs at Port Kembla in New South Wales, operated by BlueScope and Whyalla in South Australia, operated by GFG Alliance Liberty Steel. The Whyalla steelworks was placed under administration by the South Australian government in February 2025. Both of these operations use blast furnaces to produce steel using iron ore and coal. This process produces significant amounts of carbon dioxide.

**electric arc furnaces**

Modern steel making techniques utilise electric arc furnaces as replacements for blast furnaces. These use significant amounts of electricity, but are more modern and more efficient. An electric arc furnace enables the production of low-carbon steel, including green steel. Electric arc furnaces can produce steel from any combination of recycled scrap steel and direct reduced iron.

The electric arc furnace in Collie WA is able to produce steel rebar with 80% fewer emissions - from recycled steel.

In-place upgrading of blast furnaces to electric arc furnaces probably requires closure of plants. In Wales at Tata Steel, the transition shut down production for about 2 years, resulting in about 2000 people losing their job.

In the UK, a plan to replace two blast furnaces at British Steel Scunthorpe is estimated to impact up to 2,000 steel workers.

These investments have cost over 1.25bn pounds each.

**direct reduced / green iron**

Making virgin steel using an electric arc furnace requires direct reduced iron. Direct reduced iron can be produced using natural gas/coal, or with hydrogen.

proximity of whyalla steel works and port kembla steel works to iron ore mines provides an opportunity to integrate direct reduced iron production into the process.

green iron production at geraldton???

**process upgrade**

this would require upgrading blast furnaces to electric arc furnaces, or new brownfield developments meaning significant capital investment would be required.

virgin steel production should be seen as a strategic national capability to maintain.

### Legislation

There are more than 3,000 businesses operating in the iron and steel industries across Australia.

-   Multi-employer bargaining
-   Same Job Same Pay

### Government Funding

The Future Made in Australia Innovation Fund, and the National Reconstruction Fund are the primary sources for government funding for the iron and steel industry.

support for domestic produced steel (green or grey) can be provided through government purchase contracts and procurement. Demand side interventions are possibly the only way to get this kind of production from the speculation stage to actually happening. Because capital investment won't come without a guaranteed buyer. A demand side policy might look like a significant infrastructure build/development using australian produced steel.

#### Future Made in Australia

-   \$750 million to Green Metals including iron, steel, alumina and aluminium.

#### National Reconstruction Fund

-   investment in commercial opportunities for manufacturing products related to components of wind turbines, batteries, solar panels, and hydrogen electrolysers

-   investment in value-adding activities including refining materials for the use in the above.

## Conclusion

-   summary
