---
toc: true
author: Gemma Beale
---

# Just Transition

**The best worker support program will be useless without good quality jobs to transition into. The creation of good quality jobs must be a core focus of all transition plans.**

## Large scale job loss overview

Large scale job loss, industry closure, company closure, and industrial disruption are often used interchangeably – regardless, the displacement of workers as a result of this kind of disruption has been, and will continue to be, a significant feature of established and emerging economies. Whether that is because of decarbonisation, climate change, automation, structural adjustments or business model innovation (Barnes, et al., 2021; Beale, 2024) is irrelevant. The intersection of these factors is likely to lead to more frequent, wide-spread, and concurrent disruptions. Which, if not adequately addressed, will compound the more serious medium- and long-term impacts of large-scale layoffs.

Likewise, the further along the decarbonisation ‘pathway’ we progress the more complex transition becomes - as company closures become industry closures and workers become more dependent on emergent and emerging industries.

From a workers’ perspective, largescale layoffs are a similar experience regardless of the reason. In any case, large-scale job losses pose three central and interrelated problems: what happens to the workers; to the industry; and to the region - in the immediate aftermath and over the medium and long term.

The Albanese government passed the *Net Zero Authority Bill 2024* (**The Bill**) and established the Net Zero Authority (**The Authority**). Both of which cover the - whole or part - closure of a **coal-fired** or **gas-fired** **power stations.**

This document is intended as a guide for unions seeking to navigate and mitigate the impact on workers at closure of gas- and coal- fired power stations ***and*** large-scale closures and industrial disruptions not covered by The Authority. It distils learnings and best practice from recent closures in Australia to assist unions to respond quickly and effectively to the announcement of a large-scale layoffs.

The impact of any given closure both shapes, and is shaped by, the economic and regional setting in which it occurs. No two shocks are the same, and so we must be cautious about any attempts to *identically* replicate success stories - what worked in one instance will not necessarily do so in another.

Closure interventions require a clear understanding of the severity of the problem to inform the level of support needed to mitigate both the direct and indirect short-term and long-term flow-on impacts. Effective management of large-scale job losses require a holistic transition response that simultaneously considers people and place, jobs and skills, and goals and strategies - now and into the future.

This document supports early union engagement by providing an overview of the impacts and common risk factors following large scale layoffs and actions unions should consider advocating for. While the scale and shape of support may change, the components remain largely the same.

This is intended to supplement any in-house expertise and help reduce replicating work. It provides an overview of common individual and structural risk factors for workers in transition.

Past closures show us that without proper support, large-scale layoffs can have serious individual, regional and national repercussions. They can have a devastating and lasting – sometimes intergenerational - financial and psycho-social impact on workers, their families, and their communities (Spoehr, 2014; Beale, 2022; Beer, et al., 2006; Barnes & Weller, 2020).

The first step to managing an industry closure requires an understanding of the context in which the closure is occurring. A survey of the impacted workers should be undertaken as soon as possible to get a clear understanding of the workforce and tailor the response accordingly. The survey should include employer and contract type, role, qualifications and skills, age, gender, migrant status, and employment tenure. Likewise, the local employment landscape needs to be mapped to understand what opportunities are available to manage the transition.

With proper planning, an industry closure is an opportunity for industry and regional development. This requires accurate mapping of the relationship between different jobs in the region, and how best to apply the skills available in these jobs into new areas of strategic, regional, or national importance.

Workers and their communities should not be left to bear the brunt of business decisions, and a closure/transition should not be considered a success even if most of the affected population has returned to a pre-crisis level, if others have been pushed into acute stress.

## IMPACTS OF LARGE-SCALE JOB LOSS - Individual, Community and Regional

This section provides an overview of some of the serious impacts of transitions to inform and empower workers and their representatives.

### Individual Impacts

Individual impacts are not distributed evenly. Older workers, lower-paid workers, those from new migrant backgrounds, or who do not speak English fluently, are more vulnerable to periods of long-term or cyclical unemployment (Bankwest Curtin Economics, 2018).

Beyond the loss of income, large scale job loss also poses a real risk to workers physical and mental health through periods of extended unemployment and the loss of social support networks (Davies, et al., 2017). In addition to feelings of grief and loss, risks to individuals include, but are not limited to, increased rates of unhealthy behaviour (smoking, drinking, and drug misuse), anxiety and depression, higher rates of morbidity and mortality, and in serious cases suicidal ideation (Beer, et al., 2006; Marmot, et al., 2006; Beale, 2022).

This includes the exacerbation of the well-established ill-health impacts of unemployment because mass redundancy can lead to an increased competition for work, extending individual periods of unemployment and pushing the impact into the community beyond the directly impacted workforce.

A significant finding from Beale’s (2022) study of the closure of the automotive industry in South Australia was that retrenched workers who did find secure work did not report *any* poor mental health outcomes. This underscores the importance of quality of work as a protective factor for these workers.

::: callout-tip
**Effective transition programs need to invest in the social, emotional, and financial support of retrenched workers and their families. Holistic support programs are about more than *just* finding work.**
:::

### Impacts on Families

Unemployment, and specifically non-voluntary retrenchment, can also significantly impact the mental and physical health of workers’ spouses, children, and extended families. Some reports indicate that the effect on spouses’ health can be ‘almost as high’ as redundant workers (Davies, et al., 2017).

The flood of retrenched workers can displace existing job seekers who are less recently employed extending and compounding their period of unemployment.

::: callout-tip
## Recommendation

**Whenever possible transition support should be extended to the families of impacted workers and transition plans should also beware of exacerbating disadvantage in a region.**
:::

### Impacts on Community and Regions

In addition to the overarching economic environment, transition pathways are also shaped by their local and regional context. The regional context includes:

-   Contractors and the immediate supply chain

-   other businesses and industries in the region

-   the community and support networks that sustain the people who live and work there

The towns or regions in which closures occur tend to feel the impacts most acutely. However, the impacts of contemporary closures are also dispersed over a wider zone than closures of the past and are likely to extend beyond the clearly defined borders of local government (Chapain & Murie, 2008).

Single-industry regions are at greater risk of extended periods of unemployment because it is less likely that the available work will require the same skillsets as the industries shedding labour (Beale & Gamble, 2024; Beer & Evans, 2010; Spoehr, 2014).

The loss of a major employer can also have a detrimental economic impact on local business activity through the loss of income to the supply-chain as well as local stores and cafes frequented by the workforce. Inter-industry linkages mean that small businesses outside the impacted industry can suffer negative outcomes – if the population shrinks or retrenched workers reduce their spending.

The loss of cash and in-kind donations to local schools, not-for-profits and other community organisations that are common practice for larger businesses can also have serious community impacts. This might seem a flippant consideration, but these donations often make up a significant portion of a community club’s income. This is especially important given the role such organisations play as ‘third spaces’ in building community resilience and combatting social isolation.

**This is an important consideration when gathering political and community support: the impact of large-scale layoffs is not the exclusive domain of the retrenched worker.**

## PART ONE: Risk Factors and Protective Factors

This section provides a brief overview of common risk and protective factors following large scale layoffs. It provides short insight into why each factor is a concern and what action can be taken to counteract it.

### Individual Risk Factors

Transition support needs to be aware of individual risk factors. A survey of the impacted workers should be undertaken as soon as possible to get a clear understanding of the workforce and tailor the response accordingly. The survey should include employer, contract type, position, qualifications and skills, age, gender, migrant status, and employment tenure. Likewise, policy makers need to map the local employment landscape to understand what opportunities are available to manage the transition.

::: bolsh

**Effective transition programs need to conduct mapping of the workforce to identify the proportion of at-risk groups and to assist with skills mapping and matching.**

:::

#### Employment type

Transition outcomes can vary significantly between the 'main’ closing employer and contracted and supply chain workers. Historically, this has been because contracted and supply chain workers have not been able to access the same level of transition support and access to services.

::: callout-tip
## Recommendation

**All impacted workers, including those who are contractors, or linked through supply chains, must have access to the same level of transition support.**
:::

#### Age

Older workers are more vulnerable to long-term and cyclical insecure employment and unemployment (Bankwest Curtin Economics Centre, 2018; Davies et al., 2017). Older workers often find themselves working lower-quality jobs after a closure or forced into early retirement.

::: callout-tip
## Recommendation

**There is a real danger for workers who fall into the gap between being “too young to retire and too old to retrain”. Although these categories are largely socially constructed, they have been shown to have material impacts. These workers are likely to need extra and targeted support. For example, this might include digital literacy training.**
:::

#### Gender

Many of the industries most likely to be directly impacted by decarbonisation are male dominated. Male labour force participation rates have been falling for decades and non-voluntary part-time work for men has increased dramatically.

::: callout-tip
## Recommendation

**Gendered impacts manifest differently across different industries, but it is important to understand the gendered nature of the impacted workforce and of the broader industry.**
:::

#### Migrant workers

Migrant workers can be vulnerable to long periods of insecure employment or unemployment after a large-scale layoff and their experience of it may be exacerbated by the absence of citizenship rights (Barnes & Weller, 2020).

::: callout-tip
## Recommendation

**Migrant workers may need greater, and culturally and linguistically targeted, assistance to ensure they find suitable, good quality work in a timely manner.**
:::

#### Employment Tenure and Quality of Existing Work

Workers who have enjoyed long term good quality work and are financially stable may be insulated from some of the more immediate and negative aspects of industrial disruption. In contrast younger and insecurely employer workers are unlikely to have a personal financial safety net to cushion the transition.

::: callout-tip
## Recommendation

**A long tenure in a stable job may act as a protective factor but is not a guarantee. It should not be assumed older workers nearing retirement will be financially secure.**
:::

#### Transition funding and support programs

Worker’s transition funding and support programs should be made available as soon as possible and remain available for a period after retrenchment. After the auto closure, workers had to access federal, state and company funding through three separate processes – that also had separate guidelines. This was confusing and ultimately meant many workers did not access all the retraining funding that was available to them.

::: callout-tip
## Recommendation

**Workers should have access to evidence informed advice that helps them identify growth industries to increase the likelihood any training will help them get a job.**
:::

::: callout-tip
## Recommendation

**Wherever possible retraining funding should be pooled, meaning it is available in one place. As a guide, auto workers in SA were eligible for a cumulative \$3,800 to \$4,300. These figures are inclusive of State, Federal, and Company funding - the variation is dependent on whether they were working at Holden or in the supply chain.**
:::

### Structural Risk Factors

#### Quality of work

High rates of insecure work in the broader economic landscape is a pernicious problem for transition programs. Likewise, worker’s employment outcomes are unlikely to be static or linear. Workers who take on lower quality work after a closure are more likely to churn through multiple jobs and are at greater risk of experiencing negative financial and physical and mental health outcomes.

Without adequate and targeted support workers will struggle to find work of equal or greater quality than the jobs they have lost.

Historically, transition programs have focused on getting workers into new employment as quickly as possible – often at the expense of job quality. And, if present at all, their approach to job quality has often been grounded in the somewhat euphemistic ‘expectation management’ – that is, preparing workers to accept lower quality work.

::: callout-tip
## Recommendation

**Good quality jobs need to be a core focus of all transition support programs. Without targeted support it is ill-advised to assume that the first job a worker finds will be the right job and pushing workers into poor quality work just pushes the problem into the future.**
:::

#### Timing – The Importance of an Early Intervention and a Long Tail

Industrial disruption presents both short- and long- term problems: the initial wave of unemployment and then the ongoing regional socio-economic impacts. These elements are interrelated: in general, the greater forewarning workers, business, and government have of a closure, the better. Greater warning provides time to plan and, assuming the time provided by the forewarning is well utilised, the processes put in place moderate some of the more severe and lasting negative ramifications – known as the aftershocks. 

Equally important, however, is ensuring transition support has a ‘long tail’. Research from past closures warn that many of the most negative social problems do not emerge for 18 to 24 months, when retrenched workers’ payouts diminish and holidays end (Henderson & Shutt, 2004).

::: callout-tip
## Recommendation

**Early ‘intelligent intervention’ beginning with the forewarning of the closure (be it a formal announcement or otherwise) and carrying on long after the last day on the job is key to handling closures well (Spoehr, 2014; Beale, 2022).**
:::

#### Exploitative training providers

It is important to be aware of unscrupulous private training providers that can appear following the announcement of large-scale layoffs – especially if that announcement is accompanied by re-training funding for impacted workers.  

::: callout-tip
## Recommendation

**Workers should be warned and assisted to identify genuine retraining opportunities.**
:::

#### Single industry towns – population outflow

In regions highly dependent on one industry, large scale layoffs risk fuelling population outflow.

Industrial linkages mean that the impact of a closure spreads beyond the directly impacted workers to other industries in the region, causing additional employment and industry output losses.

Impacted workers may move to find work and, in serious cases, this can create a chain reaction in the broader population.
