# A Plan for Industry Development

::: callout-note
Rebuilding the manufacturing sector in Australia will not be achieved without planning. This starts with an understanding of the current structure of the economy, in conjunction with a vision for what we want the future to look like. Planning means setting targets - aligning with regional and national objectives, with specified start and end dates.
:::

## What is Industry Planning

Industry Planning is about developing a strategy for the direction of the economy. It can take two forms. One, in favour since the 1980s, prioritises market forces and price signals, letting private capital dictate the structure of the economy into one which generates the most profit. Under this approach, Australia's economy has become fundamentally weaker, with a completely hollowed out industrial structure. As such, we are now over-reliant on bulk exporting raw minerals, with the economic and social opportunities from value-added manufacturing activities occurring offshore. This approach also has led to a severe vulnerability in our economy from external shocks, and geopolitical instability. These outcomes should not be seen as inevitable. Rejecting the concept of industrial policy and strategy is itself a strategy.

The other form of Industry Planning is an active strategy which seeks to prioritise and develop certain sectors of the economy. It is primarily a strategy of identifying what we want to be able to do and what we want to be able to make. The manufacturing sector is key to this strategy. Manufacturing generates high returns to the economy, and to society, through innovation and productivity growth, investment in research and development, and its linkages to other key sectors of the economy like agriculture and mining. Active industrial policy and government interventions have been gaining traction in other parts of the world as nations seek to secure their supply chains, boost domestic manufacturing output, and create high quality jobs.

Industry Planning primarily requires an understanding of what, when, and where. It focuses on the creation of *new* markets for products and services, rather than on fixing market failures in existing sectors. These new markets are job and value creating, and are aligned with broader national missions, such as de-carbonisation or re-industrialisation.

### Planning: What

::: callout-note
Where do want to get to, given current strengths and weaknesses?
:::

Opportunity identification is a key aspect of Industry Planning. This requires **formally** identifying existing and future opportunities, and confirming these opportunities against a set of criteria, including:

-   current and future strengths and weaknesses

-   competitors and suppliers

-   international market conditions and industry demand characteristics

-   minimum efficient scale and barriers to entry

-   the size and economic significance of the opportunity

-   decisive points in the supply chain

@australianindustrialtransformationinstitute2021manufacturingtransformationhigh

Through this approach, dedicated sectoral plans can be developed, for each of the identified target industries or sectors. It is also important to consider the impact of emerging technologies and business models on the future of work, including their relevance to existing industries, and potential future industries, as well as how our current capabilities, and areas of potential competitive advantage can align with gaps and opportunities in global and domestic supply chains.

### Planning: When

::: callout-note
How do we get from where we are, to where we want to be?
:::

A pathway for development from where we are to where we want to be needs to consider specific strategies, interventions, policies and programs. Through this, sector strategy roadmaps can be developed, with defined targets and timelines. The question of timing can also be factored in for regions undergoing industry closure which need jobs.

### Planning: Where

::: callout-note
Which locations should be prioritised for targeted industry investment?
:::

Having a plan in place can help regions facing industry closure or workforce transition. Knowing what industry development to prioritise creates opportunities for job creation in regions facing job losses. Industry closure is accompanied with dates, providing a timeline for when job losses will occur, and when new jobs will be needed. Waiting for each announcement to start thinking about the number of workers affected, their skills, and support required risks regional decay, population outflow, and negative psychosocial impacts. Additionally, it is costly, time consuming, and inefficient to continually be undertaking. A plan for industry development with associated targets and timelines means that opportunities can be aligned with closures, projects are ready to roll out when required, and jobs are created in time to utilise the skills of impacted workers.

Industry Planning also has the benefit of using demand side levers to promote investment in products and services for industry to provide. The Government is thus able to use its substantial buying power through procurement policies to achieve its goals. Industry Planning focuses on the creation of new markets, not simply fixing market failures in existing markets. By defining the markets to be created, Government policy can be used as a lever to create high paying, high quality jobs, build local supply chains - providing sovereign capability, and provides a pathway for workforces impacted by industry closure to find meaningful employment in adjacent industries, and do so in a way which minimises negative impacts.
