# Rail

## Industry Overview

The rail industry comprises railway rolling stock manufacturing and repair services, as well as iron smelting and steel manufacturing which can produce the steel required to build tracks. The Australian rail industry contributed around 1.5% to the national economy in 2019, employing over 165,000 full-time equivalent people. This includes around 5,900 people in rolling stock manufacturing.

According to IBISWorld, railway equipment manufacturing and repair in Australia employs almost 10,000 people, up almost 8% since 2020, and is forecast to continue to grow by about 2% into 2030. Revenue has also grown since 2020 by about 0.5% to \$4.8bn, and is also forecast to grow by 1.5% into 2030. This growth has been driven by major rail infrastructure projects like the Melbourne Metro Tunnel and Sydney Metro. The demand induced by government spending has resulted in increasing innovation and opportunities for new business growth. The number of businesses in Australia supporting this sector has grown by almost 2% since 2020. Outstanding commitments of \$155bn through to 2030 has boosted demand for new rolling stock (both heavy and light rail), as well as ongoing repair and maintenance services.

## Opportunities

**continued infrastructure investment**

-   emphasis on energy-efficient and sustainable transport infrastructure

-   upgrading of existing rolling stock, including electrification (it might only be SA that still has diesel trains?), automation and signalling upgrades.

-   tram / track upgrades of vic light rail.

**Rail interoperability is a priority for National Cabinet** and has been a major focus for the Infrastructure and Transport Ministers Meetings (ITMM) over recent years. While the interoperability agenda has a focus on rail safety outcomes, it also has a productivity focus which can be addressed in part through national cooperation on rail procurement and manufacturing.

**State and territory governments are set to make significant investments in rolling stock**. An assessment of publicly available rolling stock procurement pipelines suggests this investment will be around \$19 billion between 2023 and 2032. This includes around 500 new passenger train and light rail vehicles across 13 known current procurements in 6 states and 2 territories. Almost two-thirds (65%) of this new rolling stock are expected to be manufactured and assembled in Australia and there is opportunity to improve outcomes through national cooperation.

**Projected population growth** in major urban and regional centres will continue to drive demand and subsequent investment in passenger and freight rail. In addition, much of Australia’s current rail infrastructure and **rolling stock is ageing and will require asset renewal over time**.

**same job same pay**

One to watch, however, I foresee that contractors may be better paid/taken care of in some instances (RE: UGL v Sydney Trains)

Very likely to be areas outside our core coverage – rail infrastructure more likely to use labour hire than rail vehicle maintenance.

That said, manufacturing of rail infrastructure (eg the actual rail, fastenings etc) is just as likely as ordinary manufacturing to use labour hire

**national reconstruction fund**

The National Reconstruction Fund Corporation may invest in the manufacture of vehicles and parts for rail including the parts and components for rail infrastructure such as sleepers.

-   

## Conclusion

-   summary

-   any other issues
